### ISSUE TITLE
test does not include example file

### ISSUE THREAD

**Issue by mblumtritt** [docopt/docopt.rb#24]
The missing example file `test/example.rb` results in test errors:

```
Error: test_option(DocoptTest)
: LoadError: cannot load such file -- example.rb
/Users/mike/prj/docopt.rb/test/test_docopt.rb:6:in `load'
/Users/mike/prj/docopt.rb/test/test_docopt.rb:6:in `setup'
```

**Comment by alexspeller** [comment]
Closing old issue, anyone still experiencing this feel free to open a new issue
